name: Scheduled Health Check

# Controls when the action will run.
on:
  workflow_dispatch:
  schedule:
    - cron: "0,15,30,45 * * * *"

jobs:
  health_check_job:
    strategy:
      matrix:
        os: ['ubuntu-latest']
    runs-on: ${{ matrix.os }}
    name: Check all sites
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install my package
        run: npm i -g pm2-windows-boot

      - name: Run Shell Script
        id: shell_script_run
        run: bash ./health-check.sh
